$(document).ready(function(){
	$(".imgHead").mousedown(function(){
		$("#up_01").css("display","none");
		$("#up_01_down").css("display","block");
	});
	$(".imgHead").mouseup(function(){
		$("#up_01").css("display","block");
		$("#up_01_down").css("display","none");
	});
});
